name: Run Azure Login with the Service Principal secret
on: [push]

jobs:
  test:
    runs-on: Self-Hosted
    steps:
    - name: Azure Login action
      uses: azure/login@v2
      with:
        creds: ${{ secrets.creds }}
        enable-AzPSSession: true
    
  
    - uses: hashicorp/setup-terraform@v3
    
    - run: terraform init --chdir=infra
